const bannedCoins = [
  "quant",
  "fantom",
  "frax share",
  "pirate chain",
  "ankr reward-bearing staked eth",
  "stratis",
  "adshares",
  "btc standard hashrate token",
  "share",
  "rsk infrastructure framework",
  "cbat",
  "santos fc fan token",
  "cratos",
  "dopex rebate",
  "ramp",
  "phantasma",
  "canto",
  "defigram",
  "mantra",
  "assetmantle",
  "battle world",
  "powerpool concentrated voting power",
  "quadrant protocol",
  "cellframe",
  "index cooperative",
  "santiment network",
  "antimatter",
  "signum",
  "stratos",
  "myconstant",
  "crowdswap",
  "ethereum push notification service - epns",
  "beethoven",
  "viberate",
  "crabada",
  "dope wars paper",
  "fantohm",
  "curate",
  "hiram",
  "filecoin standard full hashrate",
  "galactic quadrant",
  "gamma strategies",
  "billionhappiness",
  "qiibee foundation",
  "seascape crowns",
  "radiant capital",
  "battle infinity",
  "roobee",
  "cindicator",
  "humandao",
  "humaniq",
  "adamant",
  "relevant",
  "aston martin cognizant fan token",
  "crowny",
  "plant vs undead",
  "game fantasy",
  "crown",
  "piratecash",
  "dprating",
  "covenants",
  "signata",
  "grape protocol",
  "moonscape",
  "phantasia",
  "elpis battle",
  "iteration syndicate",
  "demole",
  "nami corporation",
  "flypme",
  "papel",
  "football battle",
  "signaturechain"
];

export { bannedCoins };
